name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: dean10042008
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          TIME_RANGE: all_time
          LANG_COUNT: 10
          CODE_LANG: python
          BLOCKS: ->
          SHOW_TITLE: true
          CUSTOM_TEXT: "⏳ Tracking since 25-09-2024"